// Command gendefault regenerates default_config_gen.go from the repository's
// canonical config.yaml, so the config that `la-famille init` writes can never
// drift from the documented default (#548).
//
// Run it with `go generate ./internal/config` (see the directive in
// config.go) after editing config.yaml, and commit the regenerated file.
package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
)

func main() {
	canonical := filepath.Join("..", "..", "config.yaml")
	data, err := os.ReadFile(canonical)
	if err != nil {
		fmt.Fprintf(os.Stderr, "gendefault: read %s: %v\n", canonical, err)
		os.Exit(1)
	}
	if bytes.ContainsRune(data, '`') {
		fmt.Fprintf(os.Stderr, "gendefault: %s contains a backtick and cannot be embedded in a raw string literal\n", canonical)
		os.Exit(1)
	}

	out := "// Code generated by gendefault from ../../config.yaml; DO NOT EDIT.\n" +
		"//\n" +
		"// This constant keeps the config that `la-famille init` writes byte-identical\n" +
		"// to the repository's canonical config.yaml. Edit config.yaml, then run:\n" +
		"//\n" +
		"//\tgo generate ./internal/config\n" +
		"\n" +
		"package config\n" +
		"\n" +
		"const defaultConfigYaml = `" + string(data) + "`\n"

	if err := os.WriteFile("default_config_gen.go", []byte(out), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "gendefault: write default_config_gen.go: %v\n", err)
		os.Exit(1)
	}
	fmt.Println("gendefault: wrote default_config_gen.go")
}
