package transform

import (
	"bytes"
	"strings"

	"github.com/yuin/goldmark/ast"
	"github.com/yuin/goldmark/parser"
	"github.com/yuin/goldmark/renderer"
	"github.com/yuin/goldmark/text"
	"github.com/yuin/goldmark/util"
)

// KindImageFigure identifies standalone images promoted to block-level
// figures during AST transformation.
var KindImageFigure = ast.NewNodeKind("ImageFigure")

// ImageFigure is a block node wrapping exactly one image so themes can present
// it as <figure> with an optional caption derived from the image title.
type ImageFigure struct {
	ast.BaseBlock
}

// NewImageFigure returns an empty figure block. The wrapped image must be
// appended as its only child.
func NewImageFigure() *ImageFigure {
	return &ImageFigure{}
}

// Kind implements ast.Node.
func (n *ImageFigure) Kind() ast.NodeKind {
	return KindImageFigure
}

// Dump implements ast.Node.
func (n *ImageFigure) Dump(source []byte, level int) {
	ast.DumpHelper(n, source, level, nil, nil)
}

// emojiKitchenURLFragment marks Emoji Kitchen images generated by
// EmojiKitchenParser. They are decorative inline glyphs and must keep their
// pinned inline <p><img></p> shape instead of becoming figures.
const emojiKitchenURLFragment = "emojikitchen"

// FigureTransformer promotes paragraphs that contain nothing but a single
// image into ImageFigure blocks. Images accompanied by other inline content,
// links, or Emoji Kitchen glyphs are left untouched.
type FigureTransformer struct{}

// Transform implements parser.ASTTransformer.
func (t *FigureTransformer) Transform(node *ast.Document, reader text.Reader, _ parser.Context) {
	if t == nil {
		return
	}
	promoteFigures(node, reader.Source())
}

func promoteFigures(n ast.Node, source []byte) {
	child := n.FirstChild()
	for child != nil {
		next := child.NextSibling()
		if para, ok := child.(*ast.Paragraph); ok && isStandaloneImage(para, source) {
			img := para.FirstChild().(*ast.Image)
			parent := para.Parent()
			fig := NewImageFigure()
			para.RemoveChild(para, img)
			fig.AppendChild(fig, img)
			parent.InsertBefore(parent, para, fig)
			parent.RemoveChild(parent, para)
		} else {
			promoteFigures(child, source)
		}
		child = next
	}
}

// isStandaloneImage reports whether the paragraph holds exactly one image and
// no other meaningful inline content. Whitespace-only text around the image is
// tolerated because CommonMark paragraphs routinely wrap across lines.
func isStandaloneImage(para *ast.Paragraph, source []byte) bool {
	var img *ast.Image
	for c := para.FirstChild(); c != nil; c = c.NextSibling() {
		switch n := c.(type) {
		case *ast.Image:
			if img != nil {
				return false
			}
			img = n
		case *ast.Text:
			if len(bytes.TrimSpace(n.Segment.Value(source))) > 0 {
				return false
			}
		default:
			return false
		}
	}
	if img == nil {
		return false
	}
	if strings.Contains(strings.ToLower(string(img.Destination)), emojiKitchenURLFragment) {
		return false
	}
	return true
}

// FigureRenderer renders ImageFigure blocks as semantic <figure> markup with
// lazy loading hints and an optional caption taken from the image title.
type FigureRenderer struct{}

// RegisterFuncs implements renderer.NodeRenderer.
func (r *FigureRenderer) RegisterFuncs(reg renderer.NodeRendererFuncRegisterer) {
	reg.Register(KindImageFigure, r.renderImageFigure)
}

func (r *FigureRenderer) renderImageFigure(w util.BufWriter, source []byte, node ast.Node, entering bool) (ast.WalkStatus, error) {
	if !entering {
		return ast.WalkContinue, nil
	}

	img := node.FirstChild().(*ast.Image)

	_, _ = w.WriteString(`<figure class="lf-figure"><img src="`)
	_, _ = w.Write(util.EscapeHTML(util.URLEscape(img.Destination, true)))
	_, _ = w.WriteString(`" alt="`)
	_, _ = w.Write(util.EscapeHTML([]byte(imageAltText(img, source))))
	_, _ = w.WriteString(`" loading="lazy" decoding="async"`)
	if len(img.Title) > 0 {
		_, _ = w.WriteString(` title="`)
		_, _ = w.Write(util.EscapeHTML(img.Title))
		_, _ = w.WriteString(`"`)
	}
	_, _ = w.WriteString(">")

	if len(img.Title) > 0 {
		_, _ = w.WriteString("<figcaption>")
		_, _ = w.Write(util.EscapeHTML(img.Title))
		_, _ = w.WriteString("</figcaption>")
	}

	_, _ = w.WriteString("</figure>")
	return ast.WalkSkipChildren, nil
}

// imageAltText reconstructs the alt description from the image's inline
// children, mirroring goldmark's own plain-text collection behaviour.
func imageAltText(img *ast.Image, source []byte) string {
	var buf bytes.Buffer
	for c := img.FirstChild(); c != nil; c = c.NextSibling() {
		switch n := c.(type) {
		case *ast.Text:
			buf.Write(n.Segment.Value(source))
		case *ast.String:
			buf.Write(n.Value)
		}
	}
	return buf.String()
}
