package graphexplorer

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/tbuddy/la-famille/internal/config"
)

func writeMinimumSite(t *testing.T, dir string) config.Config {
	t.Helper()
	content := filepath.Join(dir, "content")
	templates := filepath.Join(dir, "templates")
	if err := os.MkdirAll(content, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(templates, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(content, "index.md"),
		[]byte("---\ntitle: Home\n---\n# Welcome\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(content, "about.md"),
		[]byte("---\ntitle: About\n---\n# About\nLink to [home](index.md).\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(templates, "layout.html"),
		[]byte("{{.Title}} {{.Content}}"), 0o600); err != nil {
		t.Fatal(err)
	}
	return config.Config{
		SiteName:      "Test Site",
		Template:      filepath.Join(templates, "layout.html"),
		ContentDir:    content,
		OutputDir:     filepath.Join(dir, "public"),
		AssetDir:      filepath.Join(dir, "assets"),
		RagDir:        filepath.Join(dir, "rag-archive"),
		Theme:         "retro",
		Port:          8080,
		GraphExplorer: true,
	}
}

func TestWriteExplorerDisabled(t *testing.T) {
	dir := t.TempDir()
	cfg := writeMinimumSite(t, dir)
	cfg.GraphExplorer = false

	res, err := Write(cfg, 2)
	if err != nil {
		t.Fatalf("Write returned error: %v", err)
	}
	if !res.Disabled {
		t.Errorf("expected Result.Disabled=true, got %+v", res)
	}
	if res.IndexPath != "" {
		t.Errorf("expected empty IndexPath when disabled, got %q", res.IndexPath)
	}
	full := filepath.Join(cfg.OutputDir, "graph", "index.html")
	if _, err := os.Stat(full); err == nil {
		t.Errorf("expected %s not to exist when explorer disabled", full)
	}
}

func TestWriteExplorerEnabledProducesPage(t *testing.T) {
	dir := t.TempDir()
	cfg := writeMinimumSite(t, dir)

	res, err := Write(cfg, 2)
	if err != nil {
		t.Fatalf("Write returned error: %v", err)
	}
	if res.Disabled {
		t.Errorf("expected Result.Disabled=false, got %+v", res)
	}
	if res.IndexPath == "" {
		t.Fatal("expected IndexPath to be populated")
	}

	data, err := os.ReadFile(res.IndexPath)
	if err != nil {
		t.Fatalf("read explorer page: %v", err)
	}
	html := string(data)

	if !strings.Contains(html, "Knowledge Graph") {
		t.Errorf("explorer HTML missing title; got prefix: %.120s", html)
	}
	if !strings.Contains(html, `id="kgx-search-input"`) {
		t.Errorf("explorer HTML missing search input id")
	}
	// CSS and JS are external relative links now (per architecture spec).
	if !strings.Contains(html, `<link rel="stylesheet" href="../assets/graph/explorer.css">`) {
		t.Errorf("explorer HTML missing CSS link reference")
	}
	if !strings.Contains(html, `<script src="../assets/graph/explorer.js" defer>`) {
		t.Errorf("explorer HTML missing JS script reference")
	}
	// CSS and JS ship as external assets, so the page itself must NOT
	// inline them.
	if strings.Contains(html, "<style>") {
		t.Errorf("explorer HTML should not inline <style> blocks (CSS ships externally now)")
	}
	if strings.Contains(html, "<script>") || strings.Contains(html, "<script>{{") {
		t.Errorf("explorer HTML should not inline <script> blocks (JS ships externally now)")
	}
	for _, asset := range []string{"graph.json", "meta.json", "backlinks.json"} {
		if !strings.Contains(html, asset) {
			// references are inside the JS file now, not HTML; this test
			// indirectly checks via the JS file below.
			continue
		}
	}
	// Disallowed external script/font/CDN markers must NEVER appear.
	for _, bad := range []string{"https://cdn.", "//cdn.", "<script src=\"http", "googleapis.com", "jsdelivr.net", "unpkg.com", "https://fonts."} {
		if strings.Contains(html, bad) {
			t.Errorf("explorer HTML must not reference external resource: %q", bad)
		}
	}
}

func TestExplorerAssetBundlePresent(t *testing.T) {
	// The asset bundle lives under assets/graph/ and is copied by the
	// established asset pipeline. The HTML page generated by Write must
	// reference the bundle via root-relative URLs so the copy step in
	// generator.Build() makes the page fully working.
	dir := t.TempDir()
	cfg := writeMinimumSite(t, dir)
	if _, err := Write(cfg, 1); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(filepath.Join(cfg.OutputDir, "graph", "index.html"))
	if err != nil {
		t.Fatal(err)
	}
	html := string(data)
	for _, want := range []string{
		`href="../assets/graph/explorer.css"`,
		`<script src="../assets/graph/explorer.js" defer>`,
	} {
		if !strings.Contains(html, want) {
			t.Errorf("explorer HTML missing bundle reference %q", want)
		}
	}
}

func dirRoot(dir string) string {
	// helper kept for backward-compat with earlier tests
	return dir
}

func TestWriteExplorerIsByteDeterministicForSameInputs(t *testing.T) {
	dir1 := t.TempDir()
	cfg1 := writeMinimumSite(t, dir1)
	if _, err := Write(cfg1, 7); err != nil {
		t.Fatal(err)
	}
	b1, err := os.ReadFile(filepath.Join(cfg1.OutputDir, "graph", "index.html"))
	if err != nil {
		t.Fatal(err)
	}
	dir2 := t.TempDir()
	cfg2 := writeMinimumSite(t, dir2)
	if _, err := Write(cfg2, 7); err != nil {
		t.Fatal(err)
	}
	b2, err := os.ReadFile(filepath.Join(cfg2.OutputDir, "graph", "index.html"))
	if err != nil {
		t.Fatal(err)
	}
	if string(b1) != string(b2) {
		t.Errorf("explorer index.html not byte-stable across two writes\n--- a ---\n%s\n--- b ---\n%s", b1, b2)
	}
}

func TestExplorerFooterReflectsNodeCountAndThreshold(t *testing.T) {
	dir := t.TempDir()
	cfg := writeMinimumSite(t, dir)
	if _, err := Write(cfg, 42); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(filepath.Join(cfg.OutputDir, "graph", "index.html"))
	if err != nil {
		t.Fatal(err)
	}
	s := string(data)
	if !strings.Contains(s, "42 nodes") {
		t.Errorf("footer missing node count: %s", s)
	}
	if !strings.Contains(s, "500 nodes") {
		t.Errorf("footer missing large-site threshold note: %s", s)
	}
}

func TestExplorerWithSiteURLProducesCanonical(t *testing.T) {
	dir := t.TempDir()
	cfg := writeMinimumSite(t, dir)
	cfg.SiteURL = "https://example.com"
	if _, err := Write(cfg, 1); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(filepath.Join(cfg.OutputDir, "graph", "index.html"))
	if err != nil {
		t.Fatal(err)
	}
	s := string(data)
	if !strings.Contains(s, `rel="canonical" href="https://example.com/graph/"`) {
		t.Errorf("expected canonical URL, got first 600 chars: %s", pick(s, 0, 600))
	}
}

func TestExplorerWithoutSiteURLUsesRelativeLinks(t *testing.T) {
	dir := t.TempDir()
	cfg := writeMinimumSite(t, dir)
	cfg.SiteURL = ""
	if _, err := Write(cfg, 1); err != nil {
		t.Fatal(err)
	}
	data, err := os.ReadFile(filepath.Join(cfg.OutputDir, "graph", "index.html"))
	if err != nil {
		t.Fatal(err)
	}
	s := string(data)
	if strings.Contains(s, `rel="canonical"`) {
		t.Errorf("expected NO canonical tag without siteurl, got: %s", pick(s, 0, 600))
	}
	if strings.Contains(s, "<script src=\"https://") || strings.Contains(s, "https://cdn.") {
		t.Errorf("explorer must not reference external scripts: %s", pick(s, 0, 600))
	}
}

func TestExplorerPagePathIsSafe(t *testing.T) {
	// IndexPath helper must produce a child path of cfg.OutputDir; the
	// graphexplorer's boundary check (pathutil.IsSafePath) holds even when
	// OutputDir contains `..` segments because filepath.Abs canonicalises
	// them. This test therefore guards the structural invariant rather
	// than simulating an impossible escape.
	dir := t.TempDir()
	cfg := writeMinimumSite(t, dir)
	p := IndexPath(cfg.OutputDir)
	if !strings.HasSuffix(p, string(filepath.Separator)+"graph"+string(filepath.Separator)+"index.html") {
		t.Errorf("IndexPath(%q) = %q, want path ending in /graph/index.html", cfg.OutputDir, p)
	}
}

func TestExplorerAssetJSContainsExpectedAnchors(t *testing.T) {
	root, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	// From the test's perspective we walk up to the repo root; the JS file
	// lives next to the binary source.
	var jsBytes []byte
	for _, p := range []string{
		filepath.Join(root, "assets", "graph", "explorer.js"),
		filepath.Join(root, "..", "assets", "graph", "explorer.js"),
	} {
		if data, err := os.ReadFile(p); err == nil {
			jsBytes = data
			break
		}
	}
	if jsBytes == nil {
		t.Skip("assets/graph/explorer.js not found relative to test cwd; skipping anchor check")
	}
	js := string(jsBytes)
	required := []string{
		"graph.json", "meta.json", "backlinks.json",
		"LARGE_THRESHOLD",
		"selectNode", "applyFilter",
		"history.replaceState",
		"HOMEPAGE_ORPHAN_EXEMPT",
		"data-src", "data-tgt",
		"applyFocusMode",
	}
	for _, needle := range required {
		if !strings.Contains(js, needle) {
			t.Errorf("JS missing required anchor: %s", needle)
		}
	}
}

func TestExplorerAssetCSSContainsReducedMotion(t *testing.T) {
	root, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	for _, p := range []string{
		filepath.Join(root, "assets", "graph", "explorer.css"),
		filepath.Join(root, "..", "assets", "graph", "explorer.css"),
	} {
		if data, err := os.ReadFile(p); err == nil {
			if !strings.Contains(string(data), "prefers-reduced-motion") {
				t.Errorf("CSS missing reduced-motion media query")
			}
			if !strings.Contains(string(data), ".kgx-root") {
				t.Errorf("CSS missing root selector")
			}
			return
		}
	}
	t.Skip("assets/graph/explorer.css not found relative to test cwd; skipping anchor check")
}

func TestExplorerIndexPathAndRelAreStable(t *testing.T) {
	dir := t.TempDir()
	cfg := writeMinimumSite(t, dir)
	got := IndexPath(cfg.OutputDir)
	want := filepath.Join(cfg.OutputDir, "graph", "index.html")
	if got != want {
		t.Errorf("IndexPath = %q, want %q", got, want)
	}
	if IndexRel() != "graph/index.html" {
		t.Errorf("IndexRel = %q, want graph/index.html", IndexRel())
	}
	if AssetRel() != "../assets/graph/explorer" {
		t.Errorf("AssetRel = %q, want ../assets/graph/explorer", AssetRel())
	}
}

func pick(s string, offset, n int) string {
	if offset >= len(s) {
		return ""
	}
	end := offset + n
	if end > len(s) {
		end = len(s)
	}
	return s[offset:end]
}

// TestDeriveURLContract locks the public URL shape the explorer computes
// from each page id. Computing the URL client-side preserves the existing
// graph.json / meta.json / backlinks.json contracts without an extension.
func TestDeriveURLContract(t *testing.T) {
	cases := []struct{ id, want string }{
		{"index", "/"},
		{"docs/about", "/docs/about/"},
		{"research/2026", "/research/2026/"},
		{"", ""},
	}
	for _, c := range cases {
		if got := deriveURLStub(c.id); got != c.want {
			t.Errorf("deriveURLStub(%q) = %q, want %q", c.id, got, c.want)
		}
	}
}

// deriveURLStub mirrors deriveUrl() in assets/graph/explorer.js so the
// contract is locked in by Go tests rather than re-implementing logic.
func deriveURLStub(id string) string {
	if id == "" {
		return ""
	}
	if id == "index" {
		return "/"
	}
	return "/" + id + "/"
}
