package generator

import (
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"sync"
	"time"

	"github.com/tbuddy/la-famille/internal/config"
)

const cacheFileName = ".la-famille-cache.json"

// cacheVersion is bumped whenever the on-disk shape changes. Version 2 records
// a content hash per generated file instead of a bare path.
const cacheVersion = 2

// generatedFile is one file the previous build left in the output directory.
// The hash is what makes a cache hit safe: a hit republishes those bytes
// untouched, so anything that rewrote them has to force a rebuild.
type generatedFile struct {
	Path string `json:"path"`
	Hash string `json:"hash"`
}

type buildCache struct {
	Fingerprint    string          `json:"fingerprint"`
	Health         ContentHealth   `json:"health,omitempty"`
	GeneratedFiles []generatedFile `json:"generated_files"`
	Warnings       []string        `json:"warnings,omitempty"`
	Version        int             `json:"version"`
	PageCount      int             `json:"page_count"`
}

func cachePath(outputDir string) string { return filepath.Join(outputDir, cacheFileName) }

// generatorIdentity identifies the build of the generator that produced the
// output. It is a variable so tests can stand in for a different build.
var generatorIdentity = executableIdentity

// executableIdentity hashes the running binary. Output generated by a different
// build of the generator may differ even when every site input is unchanged,
// and nothing about the site reveals that, so the binary has to enter the
// fingerprint itself.
var executableIdentity = sync.OnceValue(func() string {
	if exe, err := os.Executable(); err == nil {
		if sum, hashErr := hashFile(exe); hashErr == nil {
			return sum
		}
	}
	// The generator cannot identify itself, so fall back to a value unique to
	// this process: rebuilding is cheaper than republishing stale output.
	var nonce [16]byte
	if _, err := rand.Read(nonce[:]); err != nil {
		return "unidentified-" + time.Now().UTC().Format(time.RFC3339Nano)
	}
	return "unidentified-" + hex.EncodeToString(nonce[:])
})

func cacheFingerprint(cfg config.Config, roots ...string) (string, error) {
	h := sha256.New()
	_, _ = io.WriteString(h, generatorIdentity()+"\x00")
	// WatchMode is operational state and must not invalidate generated output.
	cfg.WatchMode = false
	data, err := json.Marshal(cfg)
	if err != nil {
		return "", err
	}
	_, _ = h.Write(data)

	for _, root := range roots {
		if err := hashTree(h, root); err != nil {
			return "", err
		}
	}
	return hex.EncodeToString(h.Sum(nil)), nil
}

func hashFile(path string) (string, error) {
	f, err := os.Open(path) // #nosec G304 - callers pass paths the generator itself walked
	if err != nil {
		return "", err
	}
	defer func() { _ = f.Close() }()

	h := sha256.New()
	if _, err := io.Copy(h, f); err != nil {
		return "", err
	}
	return hex.EncodeToString(h.Sum(nil)), nil
}

// walkRootFor resolves a root that is itself a symlink. filepath.WalkDir lstats
// its root, so a symlinked content, template or asset directory is reported as
// a symlink, skipped by the traversal, and contributes nothing at all to the
// fingerprint - while the readers downstream follow the symlink and use the
// files. The result is a build that hashes an empty tree and reports cache=hit
// forever, republishing stale output after every edit.
//
// Symlinks *inside* a tree stay skipped, matching the traversal in
// internal/asset and internal/content.
func walkRootFor(root string) (string, error) {
	info, err := os.Lstat(root)
	if err != nil {
		if os.IsNotExist(err) {
			return root, nil
		}
		return "", err
	}
	if info.Mode()&os.ModeSymlink == 0 {
		return root, nil
	}
	resolved, err := filepath.EvalSymlinks(root)
	if err != nil {
		if os.IsNotExist(err) {
			// Dangling symlink: treat it like a missing root, as before.
			return root, nil
		}
		return "", err
	}
	return resolved, nil
}

func hashTree(h io.Writer, root string) error {
	walkRoot, err := walkRootFor(root)
	if err != nil {
		return err
	}

	entries := make([]string, 0)
	err = filepath.WalkDir(walkRoot, func(path string, d os.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if d.Type()&os.ModeSymlink != 0 {
			if d.IsDir() {
				return filepath.SkipDir
			}
			return nil
		}
		if d.IsDir() {
			return nil
		}
		rel, err := filepath.Rel(walkRoot, path)
		if err != nil {
			return err
		}
		entries = append(entries, filepath.ToSlash(rel))
		return nil
	})
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}
	sort.Strings(entries)
	for _, rel := range entries {
		path := filepath.Join(walkRoot, filepath.FromSlash(rel))
		contents, err := os.ReadFile(path) // #nosec G304 - path was produced by the walk above
		if err != nil {
			return err
		}
		// The configured root, not the resolved one, keys the entry: the
		// fingerprint must not change just because a symlink was introduced.
		_, _ = io.WriteString(h, filepath.ToSlash(root)+"\x00"+rel+"\x00")
		_, _ = h.Write(contents)
	}
	return nil
}

func loadBuildCache(path string) (buildCache, error) {
	var cache buildCache
	data, err := os.ReadFile(path)
	if err != nil {
		return cache, err
	}
	if err := json.Unmarshal(data, &cache); err != nil {
		return cache, err
	}
	if cache.Version != cacheVersion {
		return cache, fmt.Errorf("unsupported cache version %d", cache.Version)
	}
	return cache, nil
}

// cacheUsable reports whether the output directory still holds exactly the
// files the cache recorded, contents included. A cache hit republishes those
// bytes untouched, so anything that rewrote them must force a rebuild.
func cacheUsable(cache buildCache, outputDir, fingerprint string) bool {
	if cache.Fingerprint != fingerprint || len(cache.GeneratedFiles) == 0 {
		return false
	}
	actualFiles, err := generatedFiles(outputDir)
	if err != nil || len(actualFiles) != len(cache.GeneratedFiles) {
		return false
	}
	for i, file := range cache.GeneratedFiles {
		if file.Path == cacheFileName || filepath.IsAbs(file.Path) || strings.Contains(file.Path, "..") {
			return false
		}
		if actualFiles[i] != file {
			return false
		}
	}
	return true
}

func generatedFiles(outputDir string) ([]generatedFile, error) {
	var files []generatedFile
	err := filepath.WalkDir(outputDir, func(path string, d os.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if d.Type()&os.ModeSymlink != 0 {
			if d.IsDir() {
				return filepath.SkipDir
			}
			return nil
		}
		if d.IsDir() {
			return nil
		}
		rel, err := filepath.Rel(outputDir, path)
		if err != nil {
			return err
		}
		if filepath.Clean(rel) == cacheFileName {
			return nil
		}
		sum, err := hashFile(path)
		if err != nil {
			return err
		}
		files = append(files, generatedFile{Path: filepath.ToSlash(rel), Hash: sum})
		return nil
	})
	if err != nil {
		return nil, err
	}
	sort.Slice(files, func(i, j int) bool { return files[i].Path < files[j].Path })
	return files, nil
}

func writeBuildCache(path, fingerprint string, files []generatedFile, pageCount int, health ContentHealth, warnings []string) error {
	cache := buildCache{Version: cacheVersion, Fingerprint: fingerprint, GeneratedFiles: files, PageCount: pageCount, Health: health, Warnings: warnings}
	data, err := json.MarshalIndent(cache, "", "  ")
	if err != nil {
		return err
	}
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, append(data, '\n'), 0600); err != nil {
		return err
	}
	return os.Rename(tmp, path)
}
