package generator

import (
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"sync"
	"time"

	"github.com/tbuddy/la-famille/internal/config"
	sitediff "github.com/tbuddy/la-famille/internal/diff"
	"github.com/tbuddy/la-famille/internal/sitedata"
)

const cacheFileName = ".la-famille-cache.json"

// cacheVersion is bumped whenever the on-disk shape changes. Version 4
// retains the v2 manifest and last successful build's change ledger.
const cacheVersion = 4

// generatedFile is one file the previous build left in the output directory.
// The hash is what makes a cache hit safe: a hit republishes those bytes
// untouched, so anything that rewrote them has to force a rebuild.
type generatedFile struct {
	Path string `json:"path"`
	Hash string `json:"hash"`
}

type buildCache struct {
	Fingerprint    string            `json:"fingerprint"`
	GeneratedFiles []generatedFile   `json:"generated_files"`
	Warnings       []string          `json:"warnings,omitempty"`
	Health         ContentHealth     `json:"health,omitempty"`
	Manifest       sitedata.Manifest `json:"manifest"`
	Ledger         *sitediff.Ledger  `json:"ledger"`
	Version        int               `json:"version"`
	PageCount      int               `json:"page_count"`
}

// CachePath keeps incremental state beside the project, never inside the
// publish artifact. Direct library callers that leave ProjectRoot at "." and
// build into a temporary output get an output-specific sibling cache so tests
// and independent sites cannot share state accidentally.
func CachePath(cfg config.Config) string {
	outputAbs, err := filepath.Abs(cfg.OutputDir)
	if err != nil {
		outputAbs = filepath.Clean(cfg.OutputDir)
	}

	root := strings.TrimSpace(cfg.ProjectRoot)
	if root == "" || root == "." {
		cwd, cwdErr := filepath.Abs(".")
		if cwdErr == nil && filepath.Dir(outputAbs) == cwd && filepath.Base(outputAbs) == "public" {
			return filepath.Join(cwd, cacheFileName)
		}
		return filepath.Join(filepath.Dir(outputAbs), "."+filepath.Base(outputAbs)+cacheFileName)
	}
	return filepath.Join(root, cacheFileName)
}

// generatorIdentity identifies the build of the generator that produced the
// output. It is a variable so tests can stand in for a different build.
var generatorIdentity = executableIdentity

// executableIdentity hashes the running binary. Output generated by a different
// build of the generator may differ even when every site input is unchanged,
// and nothing about the site reveals that, so the binary has to enter the
// fingerprint itself.
var executableIdentity = sync.OnceValue(func() string {
	if exe, err := os.Executable(); err == nil {
		if sum, hashErr := hashFile(exe); hashErr == nil {
			return sum
		}
	}
	// The generator cannot identify itself, so fall back to a value unique to
	// this process: rebuilding is cheaper than republishing stale output.
	var nonce [16]byte
	if _, err := rand.Read(nonce[:]); err != nil {
		return "unidentified-" + time.Now().UTC().Format(time.RFC3339Nano)
	}
	return "unidentified-" + hex.EncodeToString(nonce[:])
})

func cacheFingerprint(cfg config.Config, roots ...string) (string, error) {
	h := sha256.New()
	_, _ = io.WriteString(h, generatorIdentity()+"\x00")
	// WatchMode stays out of the serialized config (it is operational state,
	// not site configuration), but it changes the rendered bytes — the
	// livereload script is baked into the page — so it must invalidate the
	// cache. Excluding it let a watch-mode serve republish production pages
	// without livereload, and a production build republish watch pages with
	// the script embedded (#634).
	_, _ = io.WriteString(h, map[bool]string{true: "watch", false: "build"}[cfg.WatchMode]+"\x00")
	data, err := json.Marshal(cfg)
	if err != nil {
		return "", err
	}
	_, _ = h.Write(data)

	exclude := BuildArtifactFilter(cfg)
	for _, root := range roots {
		if err := hashTree(h, root, exclude); err != nil {
			return "", err
		}
	}
	return hex.EncodeToString(h.Sum(nil)), nil
}

func hashFile(path string) (string, error) {
	f, err := os.Open(path) // #nosec G304 - callers pass paths the generator itself walked
	if err != nil {
		return "", err
	}
	defer func() { _ = f.Close() }()

	h := sha256.New()
	if _, err := io.Copy(h, f); err != nil {
		return "", err
	}
	return hex.EncodeToString(h.Sum(nil)), nil
}

// walkRootFor resolves a root that is itself a symlink. filepath.WalkDir lstats
// its root, so a symlinked content, template or asset directory is reported as
// a symlink, skipped by the traversal, and contributes nothing at all to the
// fingerprint - while the readers downstream follow the symlink and use the
// files. The result is a build that hashes an empty tree and reports cache=hit
// forever, republishing stale output after every edit.
//
// Symlinks *inside* a tree stay skipped, matching the traversal in
// internal/asset and internal/content.
func walkRootFor(root string) (string, error) {
	info, err := os.Lstat(root)
	if err != nil {
		if os.IsNotExist(err) {
			return root, nil
		}
		return "", err
	}
	if info.Mode()&os.ModeSymlink == 0 {
		return root, nil
	}
	resolved, err := filepath.EvalSymlinks(root)
	if err != nil {
		if os.IsNotExist(err) {
			// Dangling symlink: treat it like a missing root, as before.
			return root, nil
		}
		return "", err
	}
	return resolved, nil
}

func hashTree(h io.Writer, root string, exclude func(path string) bool) error {
	walkRoot, err := walkRootFor(root)
	if err != nil {
		return err
	}

	entries := make([]string, 0)
	err = filepath.WalkDir(walkRoot, func(path string, d os.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if exclude != nil && exclude(path) {
			if d.IsDir() {
				return filepath.SkipDir
			}
			return nil
		}
		if d.Type()&os.ModeSymlink != 0 {
			if d.IsDir() {
				return filepath.SkipDir
			}
			return nil
		}
		if d.IsDir() {
			return nil
		}
		rel, err := filepath.Rel(walkRoot, path)
		if err != nil {
			return err
		}
		entries = append(entries, filepath.ToSlash(rel))
		return nil
	})
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}
	sort.Strings(entries)
	for _, rel := range entries {
		path := filepath.Join(walkRoot, filepath.FromSlash(rel))
		contents, err := os.ReadFile(path) // #nosec G304 - path was produced by the walk above
		if err != nil {
			return err
		}
		// The configured root, not the resolved one, keys the entry: the
		// fingerprint must not change just because a symlink was introduced.
		_, _ = io.WriteString(h, filepath.ToSlash(root)+"\x00"+rel+"\x00")
		_, _ = h.Write(contents)
	}
	return nil
}

// BuildArtifactFilter returns a predicate reporting whether path names or
// sits inside one of the generator's own working files: the incremental build
// cache and its temp sibling, the output directory, and the transient
// .<output>.staging-* / .<output>.previous-* directories the atomic output
// swap rotates through.
//
// Flat layouts (content_dir: ".") place all of these inside the fingerprinted
// content tree. Hashing the cache file makes every fingerprint differ from
// the one just stored, so the cache can never hit; hashing a leftover staging
// or previous tree does the same, and serves none of the inputs the build
// actually reads. The watcher uses the same predicate so bookkeeping writes
// inside the watched root cannot schedule rebuilds (#633).
//
// Paths are compared in both spellings — the plain absolute form and the
// symlink-evaluated one — because the two sides cannot always share one:
// EvalSymlinks fails on a path that no longer exists (a REMOVE event for a
// deleted staging directory), while a walked tree rooted in a symlink only
// ever produces resolved paths.
func BuildArtifactFilter(cfg config.Config) func(path string) bool {
	absOf := func(path string) string {
		abs, err := filepath.Abs(path)
		if err != nil {
			return filepath.Clean(path)
		}
		return abs
	}
	resolve := func(path string) string {
		if resolved, err := filepath.EvalSymlinks(path); err == nil {
			return resolved
		}
		return path
	}

	outputAbs := absOf(cfg.OutputDir)
	outputs := map[string]bool{outputAbs: true, resolve(outputAbs): true}
	cacheAbs := absOf(CachePath(cfg))
	cacheResolved := resolve(cacheAbs)
	caches := map[string]bool{
		cacheAbs: true, cacheResolved: true,
		cacheAbs + ".tmp": true, cacheResolved + ".tmp": true,
	}
	parents := map[string]bool{}
	for out := range outputs {
		parents[filepath.Dir(out)] = true
	}
	stagingPrefix := "." + filepath.Base(outputAbs) + ".staging-"
	previousPrefix := "." + filepath.Base(outputAbs) + ".previous-"

	return func(path string) bool {
		if strings.TrimSpace(path) == "" {
			return false
		}
		abs := absOf(path)
		for _, p := range []string{abs, resolve(abs)} {
			if outputs[p] || caches[p] {
				return true
			}
			for out := range outputs {
				if strings.HasPrefix(p, out+string(filepath.Separator)) {
					return true
				}
			}
			for parent := range parents {
				if rel, err := filepath.Rel(parent, p); err == nil {
					first, _, _ := strings.Cut(filepath.ToSlash(rel), "/")
					if strings.HasPrefix(first, stagingPrefix) || strings.HasPrefix(first, previousPrefix) {
						return true
					}
				}
			}
		}
		return false
	}
}

func loadBuildCache(path string) (buildCache, error) {
	var cache buildCache
	data, err := os.ReadFile(path)
	if err != nil {
		return cache, err
	}
	if err := json.Unmarshal(data, &cache); err != nil {
		return cache, err
	}
	if cache.Version != cacheVersion {
		return cache, fmt.Errorf("unsupported cache version %d", cache.Version)
	}
	return cache, nil
}

// cacheUsable reports whether the output directory still holds exactly the
// files the cache recorded, contents included. A cache hit republishes those
// bytes untouched, so anything that rewrote them must force a rebuild.
func cacheUsable(cache buildCache, outputDir, fingerprint string) bool {
	if cache.Fingerprint != fingerprint || len(cache.GeneratedFiles) == 0 {
		return false
	}
	actualFiles, err := generatedFiles(outputDir)
	if err != nil || len(actualFiles) != len(cache.GeneratedFiles) {
		return false
	}
	for i, file := range cache.GeneratedFiles {
		if file.Path == cacheFileName || filepath.IsAbs(file.Path) || strings.Contains(file.Path, "..") {
			return false
		}
		if actualFiles[i] != file {
			return false
		}
	}
	return true
}

func generatedFiles(outputDir string) ([]generatedFile, error) {
	var files []generatedFile
	err := filepath.WalkDir(outputDir, func(path string, d os.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if d.Type()&os.ModeSymlink != 0 {
			if d.IsDir() {
				return filepath.SkipDir
			}
			return nil
		}
		if d.IsDir() {
			return nil
		}
		rel, err := filepath.Rel(outputDir, path)
		if err != nil {
			return err
		}
		if filepath.Clean(rel) == cacheFileName {
			return nil
		}
		sum, err := hashFile(path)
		if err != nil {
			return err
		}
		files = append(files, generatedFile{Path: filepath.ToSlash(rel), Hash: sum})
		return nil
	})
	if err != nil {
		return nil, err
	}
	sort.Slice(files, func(i, j int) bool { return files[i].Path < files[j].Path })
	return files, nil
}

func writeBuildCache(path, fingerprint string, files []generatedFile, pageCount int, health ContentHealth, warnings []string, manifest sitedata.Manifest, ledger *sitediff.Ledger) error {
	cache := buildCache{
		Version:        cacheVersion,
		Fingerprint:    fingerprint,
		GeneratedFiles: files,
		PageCount:      pageCount,
		Health:         health,
		Warnings:       warnings,
		Manifest:       manifest,
		Ledger:         ledger,
	}
	data, err := json.MarshalIndent(cache, "", "  ")
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0700); err != nil {
		return err
	}
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, append(data, '\n'), 0600); err != nil {
		return err
	}
	return os.Rename(tmp, path)
}
